/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tubes_kasir_f2ker;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author attau
 */
public class ManageUser extends javax.swing.JFrame {
    private int selectedId = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageUser.class.getName());

    /**
     * Creates new form AddUser
     */
    public ManageUser() {
        initComponents();
        setTitle("Dashboard Super Admin - " + SessionUser.username);
        
        cbRole.removeAllItems();
        cbRole.addItem("kasir");
        cbRole.addItem("admin");
        cbRole.addItem("super_admin");
        model.addColumn("Username");
        model.addColumn("Role");
        tblUser.setModel(model);
        tblUser.setRowSorter(rowSorter);

        tblUser.getColumnModel().getColumn(0).setPreferredWidth(200);
        tblUser.getColumnModel().getColumn(1).setPreferredWidth(100);
        tfPass.setPreferredSize(new java.awt.Dimension(90, 32)); 

        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                klikRow();
            }
        });

        loadDataUser("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        cbRole = new javax.swing.JComboBox<>();
        btnAddUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        tfPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 300));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUser);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setText("Role");

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(this::btnAddUserActionPerformed);

        btnUpdateUser.setText("Update User");
        btnUpdateUser.addActionListener(this::btnUpdateUserActionPerformed);

        btnDeleteUser.setText("Delete User");
        btnDeleteUser.addActionListener(this::btnDeleteUserActionPerformed);

        tfPass.setText("jPasswordField1");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Manage User");

        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(123, 123, 123)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeleteUser)
                            .addComponent(btnUpdateUser)
                            .addComponent(btnAddUser))))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddUser))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnUpdateUser)
                    .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        if (selectedId == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih user dari tabel terlebih dahulu!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        Connection conn = null;
        PreparedStatement ps = null;

        try {
            String username = tfName.getText().trim();
            String password = new String(tfPass.getPassword()).trim();
            String role     = cbRole.getSelectedItem().toString();

            if (username.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Username tidak boleh kosong!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/db_kasir",
                "root",
                ""
            );

            // Kalau password diisi, update sekalian — kalau kosong, skip password
            if (!password.isEmpty()) {
                if (password.length() < 6) {
                    JOptionPane.showMessageDialog(this,
                        "Password minimal 6 karakter!",
                        "Peringatan",
                        JOptionPane.WARNING_MESSAGE);
                    return;
                }
                String hashPassword = BCrypt.hashpw(password, BCrypt.gensalt());
                ps = conn.prepareStatement(
                    "UPDATE users SET username = ?, password = ?, role = ? WHERE id = ?"
                );
                ps.setString(1, username);
                ps.setString(2, hashPassword);
                ps.setString(3, role);
                ps.setInt(4, selectedId);
            } else {
                // Update tanpa ganti password
                ps = conn.prepareStatement(
                    "UPDATE users SET username = ?, role = ? WHERE id = ?"
                );
                ps.setString(1, username);
                ps.setString(2, role);
                ps.setInt(3, selectedId);
            }

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                "User berhasil diupdate!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);

            clearForm();
            loadDataUser("");
            
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal update user: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);

        } finally {
            try {
                if (ps != null)   ps.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        Connection conn = null;
        PreparedStatement ps = null;
        PreparedStatement cek = null;
        ResultSet rs = null;

        try {
            String username = tfName.getText().trim();
            String password = new String(tfPass.getPassword()).trim();
            String role     = cbRole.getSelectedItem().toString();

            if (username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Username dan password tidak boleh kosong!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (password.length() < 6) {
                JOptionPane.showMessageDialog(this,
                    "Password minimal 6 karakter!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/db_kasir",
                "root",
                ""
            );

            cek = conn.prepareStatement(
                "SELECT id FROM users WHERE username = ?"
            );
            cek.setString(1, username);
            rs = cek.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(this,
                    "Username sudah digunakan!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            String hashPassword = BCrypt.hashpw(password, BCrypt.gensalt());
            ps = conn.prepareStatement(
                "INSERT INTO users (username, password, role) VALUES (?, ?, ?)"
            );
            ps.setString(1, username);
            ps.setString(2, hashPassword);
            ps.setString(3, role);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                "User berhasil ditambahkan!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);

            clearForm();
            loadDataUser("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal tambah user: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);

        } finally {
            try {
                if (rs != null)   rs.close();
                if (cek != null)  cek.close();
                if (ps != null)   ps.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        if (selectedId == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih user dari tabel terlebih dahulu!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus user " + tfName.getText() + "?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (konfirmasi != JOptionPane.YES_OPTION) return;

        Connection conn = null;
        PreparedStatement ps = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/db_kasir",
                "root",
                ""
            );

            ps = conn.prepareStatement(
                "DELETE FROM users WHERE id = ?"
            );
            ps.setInt(1, selectedId);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                "User berhasil dihapus!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);

            clearForm();
            loadDataUser("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal hapus user: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);

        } finally {
            try {
                if (ps != null)   ps.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new DashboardUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void loadDataUser(String keyword) {
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/db_kasir",
                "root",
                ""
            );

            String sql;
            if (keyword.isEmpty()) {
                sql = "SELECT username, role FROM users ORDER BY id ASC";
                ps = conn.prepareStatement(sql);
            } else {
                sql = "SELECT username, role FROM users "
                    + "WHERE username LIKE ? "
                    + "ORDER BY id ASC";
                ps = conn.prepareStatement(sql);
                ps.setString(1, "%" + keyword + "%");
            }

            rs = ps.executeQuery();

            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("username"),
                    rs.getString("role")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal load data: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);

        } finally {
            try {
                if (rs != null)   rs.close();
                if (ps != null)   ps.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    private void clearForm() {
        tfName.setText("");
        tfPass.setText(null);
        cbRole.setSelectedIndex(0);
        selectedId = -1;
        tblUser.clearSelection();
    }
    
    private DefaultTableModel model = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
           return false;
        }
    };
    
    private TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>(model);
    
    
    private void klikRow() {
        int row = tblUser.getSelectedRow();
        if (row == -1) return;

        // Ambil data dari tabel
        String username = tblUser.getValueAt(row, 0).toString();
        String role     = tblUser.getValueAt(row, 1).toString();

        // Ambil id dari database berdasarkan username
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/db_kasir",
                "root",
                ""
            );

            ps = conn.prepareStatement(
                "SELECT id FROM users WHERE username = ?"
            );
            ps.setString(1, username);
            rs = ps.executeQuery();

            if (rs.next()) {
                selectedId = rs.getInt("id");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal ambil data: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);

        } finally {
            try {
                if (rs != null)   rs.close();
                if (ps != null)   ps.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }

        tfName.setText(username);
        tfPass.setText("");
        cbRole.setSelectedItem(role);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPass;
    // End of variables declaration//GEN-END:variables
}
