/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tubes_kasir_f2ker.Pages;

/**
 *
 * @author attau
 */
import com.mycompany.tubes_kasir_f2ker.controller.TransaksiController;
import com.mycompany.tubes_kasir_f2ker.model.SessionUser;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class DashboardTransaksi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardTransaksi.class.getName());
    private TransaksiController controller = new TransaksiController();

    private DefaultTableModel model =new DefaultTableModel() {
        @Override
        public boolean isCellEditable( int row, int column) {
            return false;
        }
    };
    /**
     * Creates new form DashboardTransaksi
     */
    public DashboardTransaksi() {
        initComponents();
        setTitle("Dashboard Transaksi - " + SessionUser.username);
        this.setLocationRelativeTo(null);
        setTitle("Dashboard Transaksi");

        model.addColumn("Nama Pegawai");
        model.addColumn("Jumlah Barang");
        model.addColumn("Total Transaksi");
        model.addColumn("Tanggal");

        tblTransaksi.setModel(model);

        tblTransaksi.getColumnModel().getColumn(0).setPreferredWidth(150);
        tblTransaksi.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblTransaksi.getColumnModel().getColumn(2).setPreferredWidth(120);
        tblTransaksi.getColumnModel().getColumn(3).setPreferredWidth(150);

        loadData("");
    }
    
    private void loadData(String keyword) {

        try {

            model.setRowCount(0);

            for (Object[] row :
                    controller.getDashboardTransaksi(
                            keyword
                    )) {

                model.addRow(row);

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        btnCari = new javax.swing.JButton();
        tfNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Fitur = new javax.swing.JMenu();
        User = new javax.swing.JMenuItem();
        Produk = new javax.swing.JMenuItem();
        Kategori = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Dashboard Transaksi");

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama pegawai", "Jumlah Barang", "Total Transaksi", "Tanggal Transaksi"
            }
        ));
        jScrollPane1.setViewportView(tblTransaksi);

        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);

        tfNama.setText("Masukan nama pegawai...");

        jLabel2.setText("List Transaksi");

        jButton1.setText("Transaksi");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        Fitur.setText("Fitur");
        Fitur.addActionListener(this::FiturActionPerformed);

        User.setText("Dashboard User");
        User.addActionListener(this::UserActionPerformed);
        Fitur.add(User);

        Produk.setText("Dasbord Produk");
        Produk.addActionListener(this::ProdukActionPerformed);
        Fitur.add(Produk);

        Kategori.setText("Dashboard Kategori");
        Kategori.addActionListener(this::KategoriActionPerformed);
        Fitur.add(Kategori);

        Transaksi.setText("Dashboard Transaksi");
        Transaksi.addActionListener(this::TransaksiActionPerformed);
        Fitur.add(Transaksi);

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        Fitur.add(jMenuItem1);

        jMenuBar1.add(Fitur);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCari))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!SessionUser.role.equals("super_admin") && !SessionUser.role.equals("kasir")) {
            JOptionPane.showMessageDialog(
                this,
                "Anda tidak memiliki akses untuk fitur ini!",
                "Akses Ditolak",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        new Transaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        new DashboardUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserActionPerformed

    private void ProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdukActionPerformed
        new DashboardProduct().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProdukActionPerformed

    private void KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriActionPerformed
        new DashboardKategori().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KategoriActionPerformed

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed
        new DashboardTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TransaksiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Login().setVisible(true);
        SessionUser.logout();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void FiturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiturActionPerformed
        new DashboardUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FiturActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardTransaksi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Fitur;
    private javax.swing.JMenuItem Kategori;
    private javax.swing.JMenuItem Produk;
    private javax.swing.JMenuItem Transaksi;
    private javax.swing.JMenuItem User;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
}
